<?php

/**
 * @file
 * Password policy password tab module installation and upgrade code.
 */

/****************************************************************************/
/* Module installation/uninstallation                                       */
/****************************************************************************/

/**
 * Implements hook_uninstall().
 */
function password_policy_password_tab_uninstall() {
  variable_del('password_policy_password_tab_redirect');
}
