<?php
/**
 * @file
 * Functionality for registration of site.
 */

/**
 * Implements hook_menu().
 */
function govcms_register_menu() {
  $items = array();
  $items['admin/config/system/register'] = array(
    'title' => 'govCMS Registration',
    'description' => 'Manage site registration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('govcms_register_form'),
    'access arguments' => array('administer site'),
  );
  return $items;
}

/**
 * Form builder.
 */
function govcms_register_form($form, &$form_state) {
  $form = array();

  $information = variable_get('govcms_register_information', array());

  $form['registration'] = govcms_register_form_elements($information);

  $form['#submit'][] = 'govcms_register_submit';
  $form['#validate'][] = 'govcms_register_validate';

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => empty($information) ? 'Register' : 'Update',
  );

  return $form;
}

/**
 * Form builder.
 *
 * @ingroup forms
 */
function govcms_register_form_elements($data = FALSE, $install = FALSE) {
  $form = array();
  $t_function = get_t();

  if (!$install) {
    $form['govcms_register_status'] = array(
      '#type' => 'item',
      '#title' => $t_function('Status'),
      '#markup' => govcms_register_status($data),
    );
  }

  if (isset($data['registered']) && $data['registered']) {

    $form['govcms_register_display_id'] = array(
      '#type' => 'item',
      '#title' => $t_function('Registration ID'),
      '#markup' => $data['govcms_register_id'],
    );

    $form['govcms_register_date'] = array(
      '#type' => 'item',
      '#title' => $t_function('Registration date'),
      '#markup' => format_date($data['govcms_register_last_attempt'], 'govcms_month_day_year'),
    );
  }

  $form['govcms_register_agency'] = array(
    '#type' => 'textfield',
    '#title' => $t_function('Department/Agency/Company'),
    '#default_value' => isset($data['govcms_register_agency']) ? $data['govcms_register_agency'] : '',
  );
  $form['govcms_register_contact'] = array(
    '#type' => 'textfield',
    '#title' => $t_function('Contact Name or Position'),
    '#default_value' => isset($data['govcms_register_contact']) ? $data['govcms_register_contact'] : '',
  );
  $form['govcms_register_email'] = array(
    '#type' => 'textfield',
    '#title' => $t_function('Contact Email'),
    '#default_value' => isset($data['govcms_register_email']) ? $data['govcms_register_email'] : '',
  );
  $form['govcms_register_notification'] = array(
    '#type' => 'checkbox',
    '#title' => $t_function('Do not send govCMS news or product update information to the registered address'),
    '#default_value' => isset($data['govcms_register_notification']) ? $data['govcms_register_notification'] : '',
  );
  $form['govcms_register_id'] = array(
    '#type' => 'hidden',
    '#value' => isset($data['govcms_register_id']) ? $data['govcms_register_id'] : '',
  );

  return $form;
}

/**
 * Validate handler.
 *
 * @ingroup forms
 */
function govcms_register_validate(&$form, &$form_state) {
  if (!valid_email_address($form_state['values']['govcms_register_email'])) {
    form_set_error('govcms_register_email', 'Please enter a valid email address.');
  }
}

/**
 * Submit handler.
 *
 * @ingroup forms
 */
function govcms_register_submit(&$form, &$form_state) {
  $data = variable_get('govcms_register_information', array());

  $data['govcms_register_agency'] = check_plain($form_state['values']['govcms_register_agency']);
  $data['govcms_register_contact'] = check_plain($form_state['values']['govcms_register_contact']);
  $data['govcms_register_email'] = check_plain($form_state['values']['govcms_register_email']);
  $data['govcms_register_notification'] = check_plain($form_state['values']['govcms_register_notification']);

  if (empty($form_state['values']['govcms_register_id'])) {
    // Generate a site id.
    $data['govcms_register_id'] = govcms_register_generate_id();
  }

  // Store the data.
  variable_set('govcms_register_information', $data);

  // Post it to the web service.
  $response = govcms_register_post($data);

  // Reload the variable data as it may have been modified.
  $data = variable_get('govcms_register_information', array());

  if ($response->code == 200) {
    drupal_set_message('Thank you, your registration was successful');
    $data['registered'] = TRUE;
  }
  else {
    drupal_set_message('Sorry, your registration failed at this time. We will try again later to register your site. If the problem persists, please contact us.', 'error');
    $data['registered'] = FALSE;
  }

  // Save the data.
  variable_set('govcms_register_information', $data);

}

/**
 * Posts's registration data to web server.
 */
function govcms_register_post($data) {
  $update_site = variable_get('govcms_update_site', 'https://updates.govcms.com.au/govcms-register');

  if (!isset($data['govcms_register_id'])) {
    $data['govcms_register_id'] = govcms_register_generate_id();
  }
  $query = drupal_http_build_query($data);

  $options = array(
    'method' => 'POST',
    'data' => $query,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  $response = drupal_http_request($update_site, $options);
  if ($response->code == 200) {
    $data['registered'] = TRUE;
  }
  else {
    $data['registered'] = FALSE;
  }
  $data['govcms_register_last_attempt'] = time();
  variable_set('govcms_register_information', $data);
  return $response;
}

/**
 * Implements hook_cron().
 */
function govcms_register_cron() {
  $data = variable_get('govcms_register_information', FALSE);

  if ($data) {
    if (empty($data['registered']) || $data['registered'] == FALSE) {
      govcms_register_post($data);
    }
  }
}

/**
 * Generates a unique id.
 * @return string
 *   unique id
 */
function govcms_register_generate_id() {

  if (function_exists('uuid_generate')) {
    return uuid_generate();
  }
  else {
    $site_name = variable_get('site_name');
    $random = rand(0, 10000);
    $string = $site_name . '_' . time() . '_' . $random;
    return md5($string);
  }

}

/**
 * Returns status of registration.
 *
 * @param array $data
 *   The registration data for the site.
 *
 * @return string
 *   The status of the registration.
 */
function govcms_register_status($data = NULL) {
  if (is_null($data)) {
    $status = 'Not registered.';
  }

  if (isset($data['registered']) && $data['registered']) {
    $status = 'Registered';
  }
  elseif (isset($data['govcms_register_last_attempt'])) {
    $status = 'Last registration attempt failed, retrying';
  }
  else {
    $status = 'Not registered';
  }
  return $status;
}
