<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function agov_permissions_form_user_profile_form_alter(&$form, $form_state) {
  if (in_array((int) variable_get('user_admin_role', 3), array_keys($form['#user']->roles), TRUE) && !user_access('assign all roles')) {
    $form['account']['status']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_alter().
 */
function agov_permissions_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'views_form_admin_views_user_system_1' && $form_state['step'] == 'views_bulk_operations_confirm_form' &&
    $form_state['operation']->operationId == 'action::views_bulk_operations_delete_item') {
    foreach (user_load_multiple($form_state['selection']) as $account) {
      if (in_array((int) variable_get('user_admin_role', 3), array_keys($account->roles), TRUE) && !user_access('assign all roles')) {
        drupal_set_message('You do not have permission to cancel this account.');
        $form['actions']['#access'] = FALSE;
        $form['description']['#access'] = FALSE;
      }
    }
  }
}
