version: '2'
services:
  cli:
    volumes:
      - .:/app:delegated
  test:
    build:
      context: .
      dockerfile: $PWD/.lagoon/Dockerfile.test
    image: test
    depends_on:
      - cli
    volumes:
      - .:/app:delegated
    volumes_from:
      - container:amazeeio-ssh-agent
  nginx:
    networks:
      - amazeeio-network
    environment:
      - WEBROOT=web
      - AMAZEEIO_URL=http://govcms.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
      - LAGOON_LOCALDEV_URL=govcms.docker.amazee.io
  php:
    environment:
      - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
  mariadb:
    ports:
      - 13306:3306
  chrome:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test
    volumes:
      - .:/app:delegated
networks:
  amazeeio-network:
    external: true
