ARG CLI_IMAGE
FROM ${CLI_IMAGE:-cli} as cli

COPY --from=cli /app /app

COPY composer.json composer.lock /app/
RUN composer install -n --ansi --prefer-dist --no-suggest
RUN drush dl drupalorg_drush -y

COPY tests /app/tests
