ARG CLI_IMAGE
FROM ${CLI_IMAGE:-cli} as cli

COPY --from=cli /app /app

COPY composer.json composer.lock phpcs.xml drupal-org.make xdebug.sh /app/
RUN composer install -n --ansi --prefer-dist --no-suggest
RUN drush dl drupalorg_drush-7.x-1.x-dev -y

COPY tests /app/tests
