<?php

/**
 * @file
 * Manages VCS-based themes on Acquia Cloud Site Factory.
 */

/**
 * Implements hook_cron().
 */
function acsf_theme_cron() {
  // When none of the notification sending succeeded then this variable will
  // contain a timestamp when the next time the cron should run to avoid
  // hammering the factory.
  $cron_next_run = acsf_vget('acsf_theme_cron_wait_until', 0);
  if ($cron_next_run < REQUEST_TIME) {
    $batch_size = acsf_vget('acsf_theme_notification_batch_size', 10);

    $notify = acsf_theme_notification();
    $success = $notify->processNotifications($batch_size);

    if ($success < 0) {
      acsf_vset('acsf_theme_cron_wait_until', time() + acsf_vget('acsf_theme_cron_delay', 600));
    }
  }
}

/**
 * Returns a new AcsfThemeNotify instance.
 */
function acsf_theme_notification() {
  return new \Acquia\Acsf\AcsfThemeNotify();
}

/**
 * Implements hook_acsf_registry().
 */
function acsf_theme_acsf_registry() {
  return array(
    'events' => array(
      array(
        'type' => 'site_duplication_scrub',
        'class' => '\Acquia\Acsf\AcsfThemeDuplicationScrubbingHandler',
        'weight' => 0,
      ),
    ),
  );
}
