<?php

/**
 * @file
 * Provides site duplication handlers.
 *
 * This is generally only needed during initial site duplication, while the
 * duplicated site is being prepared to hand off to the user.
 */

/**
 * Implements hook_acsf_registry().
 */
function acsf_duplication_acsf_registry() {
  $scrub_handlers = array(
    '\Acquia\Acsf\AcsfDuplicationScrubInitializeHandler'     => -100,
    '\Acquia\Acsf\AcsfDuplicationScrubModuleEnableHandler'   => -90,
    '\Acquia\Acsf\AcsfDuplicationScrubConfigurationHandler'  => 10,
    '\Acquia\Acsf\AcsfDuplicationScrubCommentHandler'        => 20,
    '\Acquia\Acsf\AcsfDuplicationScrubNodeHandler'           => 30,
    '\Acquia\Acsf\AcsfDuplicationScrubUserHandler'           => 40,
    '\Acquia\Acsf\AcsfDuplicationScrubTemporaryFilesHandler' => 50,
    '\Acquia\Acsf\AcsfDuplicationScrubModuleDisableHandler'  => 60,
    '\Acquia\Acsf\AcsfDuplicationScrubTruncateTablesHandler' => 70,
    '\Acquia\Acsf\AcsfDuplicationScrubFinalizeHandler'       => 100,
  );
  foreach ($scrub_handlers as $class => $weight) {
    $events[] = array(
      'type' => 'site_duplication_scrub',
      'class' => $class,
      'weight' => $weight,
    );
  }
  return array('events' => $events);
}

/**
 * Alters the scrub event context of `drush acsf-duplication-scrub-batch`.
 *
 * Use this alter hook to add optional data to the scrub event. The data added
 * here is available via the $this->event->context array in event handlers.
 *
 * @param array $data
 *   An associative array of context data needed in the event handlers.
 *
 * @see drush_acsf_duplication_scrub_batch()
 */
function acsf_duplication_acsf_duplication_scrub_context_alter(array &$data) {
  $exact_copy = drush_get_option('exact-copy');
  $options['retain_users'] = drush_get_option('retain-users', $exact_copy);
  $options['retain_content'] = drush_get_option('retain-content', $exact_copy);
  $batch = drush_get_option('batch', 1000);
  $options['batch_comment'] = drush_get_option('batch-comment', $batch);
  $options['batch_node'] = drush_get_option('batch-node', $batch);
  $options['batch_user'] = drush_get_option('batch-user', $batch);
  $data['scrub_options'] = array_merge($data['scrub_options'], $options);
}
