<?php

/**
 * @file
 * Provides core functionality for agov_twitter.
 */

define('AGOV_TWITTER_DEFAULT_TWEET_COUNT',4);
define('AGOV_TWITTER_DEFAULT_TWITTER_NAME','PreviousNext');

/**
 * Implements hook_preprocess_twitter_feed().
 */
function agov_twitter_preprocess_twitter_feed($vars) {
  drupal_add_js(drupal_get_path('module', 'agov_twitter') . '/js/jquery.tweet.js');
  drupal_add_js(drupal_get_path('module', 'agov_twitter') . '/js/gov.twitter.js');

  $settings = array(
    'twitter_feed' => array(
      'username' => $vars['username'],
      'count' => $vars['count'],
    ),
  );

  drupal_add_js($settings, 'setting');
}

/**
 * Implements hook_block_info().
 */
function agov_twitter_block_info() {
  $blocks = array();

  $blocks['feed'] = array(
    'info' => t('Twitter Feed'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function agov_twitter_block_configure($delta = '') {
  $form = array();
  if ($delta == 'feed') {
    $form['username'] = array(
      '#type' => 'textfield',
      '#title' => t('Twitter Username'),
      '#size' => 64,
      '#maxlength' => 64,
      '#default_value' => variable_get('agov_twitter_username', AGOV_TWITTER_DEFAULT_TWITTER_NAME),
    );

    $form['tweet_count'] = array(
      '#type' => 'textfield',
      '#title' => t('Tweet Count'),
      '#size' => 2,
      '#maxlength' => 2,
      '#default_value' => variable_get('agov_twitter_count', AGOV_TWITTER_DEFAULT_TWEET_COUNT),
    );
  }
  return $form;
}


/**
 * Implements hook_block_save().
 */
function agov_twitter_block_save($delta = '', $edit = array()) {
  if ($delta == 'feed') {
    variable_set('agov_twitter_count', $edit['tweet_count']);
    variable_set('agov_twitter_username', $edit['username']);
  }
}

/**
 * Implements hook_block_view().
 */
function agov_twitter_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'feed':
      $username = variable_get('agov_twitter_username', AGOV_TWITTER_DEFAULT_TWITTER_NAME);
      $count = variable_get('agov_twitter_count', AGOV_TWITTER_DEFAULT_TWEET_COUNT);

      $block['subject'] = "Twitter feed";
      $variables = array(
        'username' => check_plain($username),
        'count' => $count,
      );
      $block['content'] = theme('twitter_feed', $variables);

      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function agov_twitter_theme() {
  return array(
    'twitter_feed' => array(
      'variables' => array(
        'username' => NULL,
        'count' => NULL,
      ),
      'template' => 'theme/twitter-feed',
    ),
  );
}
