<?php
/**
 * @file
 * Functionality for registration of site.
 */

/**
 * Implements hook_menu().
 */
function agov_register_menu() {
  $items = array();
  $items['admin/register'] = array(
    'title' => 'aGov Registration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agov_register_form'),
    'access arguments' => array('administer site'),
  );
  return $items;
}

/**
 * Form builder.
 */
function agov_register_form() {
  $agov_register_information = variable_get('agov_register_information', FALSE);

  $form = array();

  if ($agov_register_information['registered']) {
    drupal_set_message('Your installation is registered. It was last updated on ' . format_date($agov_register_information['agov_register_last_attempt'], 'agov_month_day_year'));
  }
  elseif (isset($agov_register_information['last_attempt'])) {
    drupal_set_message('the previous attempt to register your installation on ' . format_date($agov_register_information['last_attempt'], 'agov_month_date_year') . ' was not successful. We will attempt to register it at another time. If this problem persists, please visit agov.com.au/support');
  }
  else {
    drupal_set_message('Your installation is not currently registered. Please fill out the following information to register.', 'warning');
  }

  $form['registration'] = agov_register_form_elements($agov_register_information);

  $form['#submit'][] = 'agov_register_submit';
  $form['#validate'][] = 'agov_register_validate';

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => empty($agov_register_information) ? 'Register' : 'Update',
  );
  return $form;
}

/**
 * Form builder.
 */
function agov_register_form_elements($data = FALSE) {
  $t = get_t();
  $form = array();
  $form['agov_register_agency'] = array(
    '#type' => 'textfield',
    '#title' => $t('Department/Agency/Company'),
    '#default_value' => isset($data['agov_register_agency']) ? $data['agov_register_agency'] : '',
  );
  $form['agov_register_contact'] = array(
    '#type' => 'textfield',
    '#title' => $t('Contact Name or Position'),
    '#default_value' => isset($data['agov_register_contact']) ? $data['agov_register_contact'] : '',
  );
  $form['agov_register_email'] = array(
    '#type' => 'textfield',
    '#title' => $t('Contact Email'),
    '#default_value' => isset($data['agov_register_email']) ? $data['agov_register_email'] : '',
  );
  $form['agov_register_notification'] = array(
    '#type' => 'checkbox',
    '#title' => $t('Do not send aGov news or product update information to the registered address'),
    '#default_value' => isset($data['agov_register_notification']) ? $data['agov_register_notification'] : '',
  );
  $form['agov_register_id'] = array(
    '#type' => 'hidden',
    '#value' => isset($data['agov_register_id']) ? $data['agov_register_id'] : '',
  );

  return $form;
}

/**
 * Validate handler.
 */
function agov_register_validate(&$form, &$form_state) {
  if (!valid_email_address($form_state['values']['agov_register_email'])) {
    form_set_error('agov_register_email', 'Please enter a valid email address.');
  }
}

/**
 * Submit handler.
 */
function agov_register_submit(&$form, &$form_state) {

  $data = variable_get('agov_register_information', array());

  $data['agov_register_agency'] = check_plain($form_state['values']['agov_register_agency']);
  $data['agov_register_contact'] = check_plain($form_state['values']['agov_register_contact']);
  $data['agov_register_email'] = check_plain($form_state['values']['agov_register_email']);
  $data['agov_register_notification'] = check_plain($form_state['values']['agov_register_notification']);

  if (empty($form_state['values']['agov_register_id'])) {
    // Generate a site id.
    $data['agov_register_id'] = agov_register_generate_id();
  }

  // Store the data.
  variable_set('agov_register_information', $data);

  // Post it to the web service.
  $response = agov_register_post($data);

  // Reload the variable data as it may have been modified.
  $data = variable_get('agov_register_information', array());

  if ($response->code != 200) {
    $data['registered'] = FALSE;
  }

  // Save the data.
  variable_set('agov_register_information', $data);
}

/**
 * Post function.
 */
function agov_register_post($data) {
  $update_site = variable_get('agov_update_site', 'http://updates.agov.com.au');
  $query = drupal_http_build_query($data);
  $response = drupal_http_request($update_site . '/update_check?' . $query);
  if ($response->code == 200) {
    $data['registered'] = TRUE;
  }
  else {
    $data['registered'] = FALSE;
  }
  $data['agov_register_last_attempt'] = time();
  variable_set('agov_register_information', $data);
  return $response;
}

/**
 * Implements hook_cron().
 */
function agov_register_cron() {

  $data = variable_get('agov_register_information', FALSE);

  if ($data) {
    if (empty($data['registered']) || $data['registered'] == FALSE) {
      agov_register_post($data);
    }
  }
}

/**
 * Generates a unique id.
 * @return string
 *   unique id
 */
function agov_register_generate_id() {

  if (function_exists('uuid_generate')) {
    return uuid_generate();
  }
  else {
    $site_name = variable_get('site_name');
    $random = rand(0, 10000);
    $string = $site_name . '_' . time() . '_' . $random;
    return md5($string);
  }

}
