<?php
/**
 * @file
 * Code for the Configuration Utility feature.
 */

/**
 * Implements hook_permission().
 */
function govcms_config_util_permission() {
  return array(
    'access govcms_config_util page' => array(
      'title' => t('Access the govCMS configuration page.'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function govcms_config_util_menu() {
  $items = array();
  $items['admin/config/system/govcms_site_configuration'] = array(
    'title' => 'govCMS Site Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('govcms_config_util_admin'),
    'access arguments' => array('access govcms_config_util page'),
    'type' => MENU_NORMAL_ITEM, //Will appear in Navigation menu.
  );
  return $items;
}

function govcms_config_util_admin() {
  // Date settings:
  $zones = system_time_zones();

  $form = array();

  $form['site_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Site Name'),
    '#default_value' => variable_get('site_name'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t("The site name"),
    '#required' => TRUE,
  );

  $form['site_slogan'] = array(
    '#type' => 'textfield',
    '#title' => t('Slogan'),
    '#default_value' => variable_get('site_slogan'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t("How this is used depends on your site's theme."),
    '#required' => FALSE,
  );

  $form['site_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail address'),
    '#default_value' => variable_get('site_mail'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t("The From address in automated e-mails sent during registration and new password requests, and other notifications. (Use an address ending in your site's domain to help prevent this e-mail being flagged as spam.)"),
    '#required' => TRUE,
  );

  $form['date_default_timezone'] = array(
    '#type' => 'select',
    '#title' => t('Default time zone'),
    '#default_value' => variable_get('date_default_timezone', date_default_timezone_get()),
    '#options' => $zones,
  );

  return system_settings_form($form);
}

function govcms_config_util_admin_validate($form, &$form_state) {
  $site_mail = $form_state['values']['site_mail'];
  if (!valid_email_address($site_mail)) {
    form_set_error('site_mail', t('The e-mail address %mail is not valid.', array('%mail' => $site_mail)));
  }
}

