<?php
/**
 * @file
 * user_action_report.module
 */

/**
 * Implements hook_permission().
 */
function user_action_report_permission() {
  return array(
    'view user actions' => array(
      'title' => t('View User Actions'),
      'description' => t('View user actions such as logging in and adding/updating content.'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function user_action_report_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}
