<?php

/**
 * @file
 * Allows users and system to add AGLS meta tags to Drupal pages.
 *
 * @copyright Copyright(c) 2013 Previous Next Pty Ltd
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Kim Pepper kim at previousnext dot com dot au
 * @author Nick Schuch nick at previousnext dot com dot au
 * @author Chris Skene chris at previousnext dot com dot au
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function agls_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function agls_preprocess_html(&$vars) {

  $element = array(
    '#tag' => 'link',
    '#attributes' => array(
      'rel' => 'schema.AGLSTERMS',
      'href' => 'http://www.agls.gov.au/agls/terms/',
    ),
  );

  drupal_add_html_head($element, 'agls_schema');
}
