<?php

/**
 * @file
 * Provides core functionality for node_freshness.
 */

/************* CORE HOOKS ************/

/**
 * Implements hook_views_api().
 */
function node_freshness_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'node_freshness') . '/views',
  );
}

/**
 * Implements hook_permission().
 */
function node_freshness_permission() {
  return array(
    'can administer node freshness settings' => array(
      'title' => t('Administer Node Freshness'),
      'description' => t('Allows users to be able to manage Node Freshness.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function node_freshness_menu() {
  $items = array();

  // Admin settings page callback.
  $items['admin/config/content/node-freshness'] = array(
    'title' => 'Node Freshness',
    'description' => 'This pages configures Node Freshness.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_freshness_config'),
    'access arguments' => array('can administer node freshness settings'),
    'file' => 'node_freshness.admin.inc',
  );

  return $items;
}

/************* UTILITY FUNCTIONS *************/

/**
 * Returns freshness diff in unix time.
 */
function _node_freshness_get() {
  // Get the default values.
  $values = variable_get('node_freshness', array('node_freshness_amount' => '6', 'node_freshness_type' => 'month'));

  // Calculate the strtotime value.
  $string = '-' . $values['node_freshness_amount'] . ' ' . $values['node_freshness_type'];
  $values['value'] = format_date(strtotime($string), 'custom', $format = 'Y-m-d H:i:s');

  return $values;
}
