<?php

/**
 * @file
 * Provides core functionality for agov_content_requirements.
 */

/**
 * Implements hook_form_BASE_FORM_alter().
 *
 * Creates a section at the top of node creation/editing
 * forms for displaying content requirements
 */
function agov_content_requirements_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Include our ctools code.
  ctools_include('modal');
  ctools_modal_add_js();

  // Make sure we are at the top of the form.
  $weight = $form['title']['#weight'] - 1;

  $form['content_requirements'] = array(
    '#markup' => l(t('Content Requirements'), 'admin/agov-content-requirements/nojs', array('attributes' => array('class' => 'ctools-use-modal'))),
    '#weight' => $weight,
  );
}

/**
 * Create our config form.
 */
function agov_content_requirements_form($form, &$form_state) {
  $form['agov_content_requirements_text'] = array(
    '#type' => 'text_format',
    '#title' => t('Content Requirements'),
    '#default_value' => agov_content_requirements_get_text(),
    '#description' => t('The text to display when the popup is loaded.'),
  );

  $form['agov_content_requirements_link'] = array(
    '#type' => 'textfield',
    '#title' => t('More Info URL'),
    '#default_value' => agov_content_requirements_get_link(),
  );

  return system_settings_form($form);
}

/**
 * View the requirements page content.
 */
function agov_content_view_requirements($js = FALSE) {
  $title = t('Content Requirements');
  $output = agov_content_requirements_get_text() . '<p>' . l(t('More Info'), agov_content_requirements_get_link(), array('attributes' => array('target' => '_blank'))) . '</p>';

  // Make sure our output suits our medium - modal or page.
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_modal_render($title, $output);
  }
  else {
    drupal_set_title($title);
    return $output;
  }
}

/**
 * Implements hook_menu().
 *
 * Define our system settings form page.
 */
function agov_content_requirements_menu() {
  // Our admin config page.
  $items['admin/config/content/agov-content-requirements'] = array(
    'title' => 'Content Requirements',
    'description' => 'Administer the content requirements information for content editors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agov_content_requirements_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Our requirements display page for the modal.
  $items['admin/agov-content-requirements/%ctools_js'] = array(
    'title' => 'Content Requirements',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'agov_content_view_requirements',
    'page arguments' => array(2),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * We have a txt file with the requirements in it for default use.
 */
function agov_content_requirements_get_text() {
  // As the variable contains a format, we need it in an array.
  // If the var doesnt exist, we'll create an array containing the default text.
  $default = array(
    'format' => 'filtered_html',
    'value' => file_get_contents(drupal_get_path('module', 'agov_content_requirements') . '/agov_content_requirements.txt'),
  );
  $text = variable_get('agov_content_requirements_text', $default);

  return check_markup($text['value'], $text['format']);
}

/**
 * Returns the agov_content_requirements_link variable.
 */
function agov_content_requirements_get_link() {
  return variable_get('agov_content_requirements_link', 'http://webguide.gov.au/required-information/online-content-requirements/');
}
