<?php

/**
 * @file
 * Provides core functionality for govcms_menu_block.
 */

/**
 * Implements hook_menu_block_blocks().
 */
function govcms_menu_block_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'govcms_menu_block-main-menu' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Menu (Expanded)',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
    'govcms_menu_block-footer' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Footer Menu',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
    'govcms_menu_block-sidebar' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 2,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
