<?php

/**
 * @file
 * Logs node CRUD commands in the event_log module.
 *
 * @author Bas van Meurs
 * @copyright Cipix Internet
 */

/**
 * Implements hook_event_log_handlers().
 * @return array
 */
function event_log_node_event_log_handlers() {
  // Node event log handler.
  $handlers = array();
  $handlers['node'] = array(
    'title' => t('Node'),
    'relationships' => array(
      array(
        'table' => 'node',
        'field' => 'nid',
        'operations' => NULL,
        'numeric' => TRUE,
      ),
    ),
  );
  return $handlers;
}

/**
 * Implements hook_node_insert().
 */
function event_log_node_insert($node) {
  $log = array(
    'type' => 'node',
    'operation' => 'insert',
    'description' => t('%type: %title', array(
      '%type' => $node->type,
      '%title' => $node->title
    )),
    'ref_numeric' => $node->nid,
  );
  event_log_insert($log);
}

/**
 * Implements hook_node_update().
 */
function event_log_node_update($node) {
  $log = array(
    'type' => 'node',
    'operation' => 'update',
    'description' => t('%type: %title', array(
      '%type' => $node->type,
      '%title' => $node->title
    )),
    'ref_numeric' => $node->nid,
    'info' => $node->original,
  );
  event_log_insert($log);
}

/**
 * Implements hook_node_delete().
 */
function event_log_node_delete($node) {
  $log = array(
    'type' => 'node',
    'operation' => 'delete',
    'description' => t('%type: %title', array(
      '%type' => $node->type,
      '%title' => $node->title
    )),
    'ref_numeric' => $node->nid,
    'info' => $node,
  );
  event_log_insert($log);
}

/**
 * Implements hook_init().
 */
function event_log_node_init() {
  if (variable_get('event_log_node_log_views', 1)) {
    if ($node = menu_get_object()) {
      $log = array(
        'type' => 'node',
        'operation' => 'view',
        'description' => (mb_strlen($node->title) > 20 ? mb_substr($node->title, 0, 20) . '...' : $node->title),
        'ref_numeric' => $node->nid,
      );
      event_log_insert($log);
    }
  }
}
