<?php

/**
 * @file
 * Provides core functionality
 */

/**
 * Provides modules to be controlled by this module.
 */
function agov_disable_defaultcontent_list() {
  return array(
    'agov_content_event',
    'agov_content_publication',
    'agov_content_blog',
    'agov_content_media_release',
    'agov_content_news_article',
    'agov_content_promotion',
    'agov_content_standard_page',
  );
}

/**
 * Implements hook_menu().
 */
function agov_disable_defaultcontent_menu() {
  $items = array();
  $items['disable-default-content'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agov_disable_defaultcontent_disable_modules'),
    'access arguments' => array('administer site'),
  );
  return $items;
}

/**
 * To avoid CSRF we setup a confirm form first.
 */
function agov_disable_defaultcontent_disable_modules($form, &$form_state) {
  return confirm_form($form, 'Disable aGov default content?', '');
}

/**
 * Handles disabling all content modules.
 */
function agov_disable_defaultcontent_disable_modules_submit($form, &$form_state) {
  $default_content = agov_disable_defaultcontent_modules();
  if (!empty($default_content)) {
    // Enabled, switch if off.
    module_disable($default_content);
    drupal_set_message(t('Default content has been turned off.'), 'status', FALSE);

    // Remove the tags.
    $tids = variable_get('agov_tags_saved', FALSE);

    // Ensure we have values to delete.
    if (!empty($tids)) {
      // Delete the taxonomies.
      foreach ($tids as $tid) {
        taxonomy_term_delete($tid);
      }

      // Clean up the variables.
      variable_del('agov_tags_saved');

      // Delete About us bean on homepage.
      $bean = bean_load_delta('about-us');
      bean_delete($bean);
    }
  }

  drupal_flush_all_caches();
  drupal_goto();
}

/**
 * Implements hook_init().
 */
function agov_disable_defaultcontent_init() {
  // Check if an install task variable exists so that we do not display this
  // message just after the content has been installed.
  $install_task = variable_get('install_task');
  if ($install_task == 'done' && user_access('administer site') && current_path() != 'disable-default-content') {
    $default_content = agov_disable_defaultcontent_modules();
    if (!empty($default_content)) {
      drupal_set_message(t('Default content has been enabled for this site, would you like to <a href="!url">switch if off?</a>', array('!url' => url('disable-default-content'))), 'status', FALSE);
    }
  }
}

/**
 * Returns an array of enabled content modules if any.
 */
function agov_disable_defaultcontent_modules() {
  // Variables.
  $enabled_content = array();

  // Get a list of enabled modules.
  $enabled_modules = array_values(module_list());

  // Get our list of modules.
  $agov_modules = agov_disable_defaultcontent_list();

  // We now run a comparison to see if any are enabled.
  foreach ($agov_modules as $agov_module) {
    if (in_array($agov_module, $enabled_modules)) {
      $enabled_content[] = $agov_module;
    }
  }

  return $enabled_content;
}
