FROM amazeeio/php:7.1-cli-drupal

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY tests/composer.json tests/composer.lock /app/tests/
RUN echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/memory.ini \
    && composer install -d /app/tests -n --ansi --prefer-dist --no-suggest \
    && drush dl drupalorg_drush-7.x-1.x-dev -y \
    && rm -rf /usr/local/etc/php/conf.d/memory.ini

COPY --from=govcms/govcms7 /app /app

COPY tests /app/tests
