#!/usr/bin/env bash
# Code linting for SaaS project.

APP_DIR=${APP_DIR:-/app}
PROFILE_DIR=${PROFILE_DIR:-${APP_DIR}/profiles/govcms}

# Lint code.
${APP_DIR}/tests/vendor/bin/parallel-lint --exclude /app/tests/vendor -e php,inc,module,theme,install,profile,test ${PROFILE_DIR}/themes/custom

# Check code standards.
${APP_DIR}/tests/vendor/bin/phpcs --standard=${PROFILE_DIR}/phpcs.xml ${PROFILE_DIR}/themes/custom

# Check code mess.
${APP_DIR}/tests/vendor/bin/phpmd --ignore-violations-on-exit ${PROFILE_DIR}/themes/custom text codesize,unusedcode,cleancode
