<?php

/**
 * @file
 * The main Iconomist module file.
 *
 * Iconomist is module that allows you to add icons to your drupal site
 * for example adding Apple touch icons for iPhone, iPad etc. Each device
 * supports a different size icon so the module allows you to upload multiple
 * icons and set the dimension for that icon.
 */

use Drupal\Iconomist\Iconomist as Iconomist;

require_once drupal_get_path('module', 'iconomist') . '/iconomist.class.php';

/**
 * Implements hook_form_system_theme_settings_alter().
 */
function iconomist_form_system_theme_settings_alter(&$form, &$form_state) {
  Iconomist::themeSettingsAlter($form, $form_state);
}

/**
 * Ajax callback to add an icon.
 *
 * @param array $form
 *   The form render array.
 * @param array &$form_state
 *   The form state array.
 */
function _iconomist_add_icon(array $form, array &$form_state) {
  Iconomist::addIcon($form, $form_state);
}

/**
 * Ajax callback to remove an icon.
 *
 * @param array $form
 *   The form render array.
 * @param array &$form_state
 *   The form state array.
 */
function _iconomist_remove_icon(array $form, array &$form_state) {
  Iconomist::removeIcon($form, $form_state);
}

/**
 * AJAX callback for rendering iconomist container.
 *
 * @param array $form
 *   The form render array.
 * @param array $form_state
 *   The form state array.
 */
function _iconomist_ajax_callback(array $form, array $form_state) {
  return Iconomist::ajaxCallback($form, $form_state);
}

/**
 * Validate custom plain touch icon settings.
 *
 * @param array $element
 *   The form render array.
 * @param array &$form_state
 *   The form state array.
 */
function _iconomist_icons_validate(array $element, array &$form_state) {
  Iconomist::validate($element, $form_state);
}

/**
 * Custom theme settings submit handler.
 *
 * @param array $form
 *   The form render array.
 * @param array &$form_state
 *   The form state array.
 */
function _iconomist_settings_submit(array $form, array &$form_state) {
  Iconomist::settingsSubmit($form, $form_state);
}

/**
 * Implements hook_preprocess_html().
 */
function iconomist_preprocess_html(&$vars) {
  Iconomist::preprocessHtml($vars);
}
