<?php
/**
 * @file
 * Sets up include for feature.
 */

include_once 'govcms_editing.features.inc';

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function govcms_editing_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['scayt_autoStartup'] = TRUE;
    // UI language.
    $settings['language'] = 'en-gb';
    // Spell Check As You Type language.
    $settings['scayt_sLang'] = 'en_GB';
    // Check Spelling button language.
    $settings['wsc_lang'] = 'en_GB';
  }
}
