<?php
/**
 * @file
 * agov_content_slides.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function agov_content_slides_content_defaults() {
  $content = array();

  $content['slide_1'] = (object) array(
    'exported_path' => 'os-praemitto-refero-tation',
    'title' => 'Os Praemitto Refero Tation',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'slide',
    'language' => 'und',
    'created' => 1358207932,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'slide_1',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Appellatio autem natu os. Cui ex plaga similis tamen veniam. Brevitas in nimis quae tum vel. Appellatio nimis nunc ratis vel. Distineo gilvus pneum quia quidne tamen vereor.&nbsp;</p>',
          'summary' => '',
          'format' => 'rich_text',
          'safe_value' => ' <p>Appellatio autem natu os. Cui ex plaga similis tamen veniam. Brevitas in nimis quae tum vel. Appellatio nimis nunc ratis vel. Distineo gilvus pneum quia quidne tamen vereor.&nbsp;</p> ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_read_more' => array(
      'und' => array(
        0 => array(
          'url' => 'about-us',
          'title' => 'Read more',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slide_image' => array(
      'und' => array(
        0 => array(
          'alt' => 'Os Praemitto Refero Tation',
          'title' => NULL,
          'width' => 900,
          'height' => 637,
          'filename' => 'bigstock-Conference-26104.jpg',
          'uri' => 'public://bigstock-Conference-26104.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 999455,
          'status' => 1,
          'type' => 'image',
          'uuid' => '146f3368-0165-4a45-afd4-5fd1279d7675',
          'metatags' => array(),
          'rdf_mapping' => array(),
          'image_dimensions' => array(
            'width' => 900,
            'height' => 637,
          ),
        ),
      ),
    ),
  );

  $content['slide_2'] = (object) array(
    'exported_path' => 'diam-eum-probo',
    'title' => 'Diam Eum In Probo',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'slide',
    'language' => 'und',
    'created' => 1358207932,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'slide_2',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Appellatio dolus eligo ideo patria refoveo valde valetudo. Adipiscing aliquip lenis melior minim nisl te valde. Ex illum occuro tego vulputate. Gravis ibidem meus rusticus.&nbsp;</p>',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Appellatio dolus eligo ideo patria refoveo valde valetudo. Adipiscing aliquip lenis melior minim nisl te valde. Ex illum occuro tego vulputate. Gravis ibidem meus rusticus. </p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_read_more' => array(
      'und' => array(
        0 => array(
          'url' => 'news-media',
          'title' => 'Read more',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slide_image' => array(
      'und' => array(
        0 => array(
          'alt' => 'Diam Eum In Probo',
          'title' => NULL,
          'width' => 900,
          'height' => 522,
          'filename' => 'bigstock-Australian-Soldiers-2673666.jpg',
          'uri' => 'public://bigstock-Australian-Soldiers-2673666.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 486272,
          'status' => 1,
          'type' => 'image',
          'uuid' => '90d01526-2064-4fe2-9ad8-cc5a104448c4',
          'metatags' => array(),
          'rdf_mapping' => array(),
          'image_dimensions' => array(
            'width' => 900,
            'height' => 522,
          ),
        ),
      ),
    ),
  );

  $content['slide_3'] = (object) array(
    'exported_path' => 'macto-oppeto',
    'title' => 'Macto Oppeto',
    'status' => 1,
    'promote' => 0,
    'sticky' => 0,
    'type' => 'slide',
    'language' => 'und',
    'created' => 1358207932,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'slide_3',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Eligo gilvus molior tation virtus. Bene camur eros. Autem diam feugiat jugis mos pagus quidne similis vel venio. Obruo ratis saluto suscipit. Abluo utinam uxor.</p>',
          'summary' => '',
          'format' => 'rich_text',
          'safe_value' => ' <p>Eligo gilvus molior tation virtus. Bene camur eros. Autem diam feugiat jugis mos pagus quidne similis vel venio. Obruo ratis saluto suscipit. Abluo utinam uxor.</p> ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_read_more' => array(
      'und' => array(
        0 => array(
          'url' => 'services',
          'title' => 'Read more',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slide_image' => array(
      'und' => array(
        0 => array(
          'alt' => 'Macto Oppeto',
          'title' => NULL,
          'width' => 900,
          'height' => 600,
          'filename' => 'bigstock-Koala-3496163.jpg',
          'uri' => 'public://bigstock-Koala-3496163.jpg',
          'filemime' => 'image/jpeg',
          'filesize' => 662642,
          'status' => 1,
          'type' => 'image',
          'uuid' => 'a5c9c5c6-cbef-4401-a618-7b1d8a2c03bc',
          'metatags' => array(),
          'rdf_mapping' => array(),
          'image_dimensions' => array(
            'width' => 900,
            'height' => 600,
          ),
        ),
      ),
    ),
  );

return $content;
}
