<?php

/**
 * @file
 * Guzzle HTTP client library
 *
 * This module uses the composer autoloader to initialise the Guzzle library.
 */

/**
 * Implements hook_init().
 */
function guzzle_init() {
  guzzle_classloader();
}

/**
 * Implements hook_help().
 */
function guzzle_help($path, $arg) {
  $output = '';

  switch ($path) {
    case 'admin/help#guzzle':
      // Display the introduction paragraph.
      $output .= '<p>' . t('<a href="@guzzle">Guzzle</a> is a PHP framework for web projects. Speed up the creation and maintenance of your PHP web applications. Replace the repetitive coding tasks by power, control and pleasure.</p>', array(
        '@guzzle' => 'http://guzzlephp.org',
      ));

      // Test out using the module if we're actually on the help page.
      if ($_GET['q'] == 'admin/help/guzzle') {
        $output .= '<h3>' . t('Guzzle Example') . '</h3>';
        $client = new Guzzle\Service\Client('http://drupal.org');
        $response = $client->get('/download')->send();
        $output .= '<pre>' . print_r($response, TRUE) . '</pre>';
      }
  }

  return $output;
}

/**
 * Loads the class loader in order to register all Guzzle namespaces.
 */
function guzzle_classloader() {
  static $loader = NULL;

  // Load Composer's autoloader to expose Guzzle.
  if (!isset($loader)) {
    // The vendor can either be in modules/guzzle/vendor, or sites/all/vendor.
    foreach (array(__DIR__, dirname(dirname(__DIR__))) as $path) {
      $loader = @include_once $path . '/vendor/autoload.php';
      if ($loader) {
        return $loader;
      }
    }

    // Display a warning about the autoloader not being able to load.
    if (!$loader) {
      $message = t('You must install Guzzle by running a Composer install from the %path directory.', array(
        '%path' => __DIR__,
      ));
      drupal_set_message($message, 'warning', FALSE);
    }
  }

  return $loader;
}
